// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getFoldersWithDocuments() : Promise<Result<UserFolder[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folders_with_documents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecentDocuments(limit: number | null, offset: number | null) : Promise<Result<RecentDocumentsResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_documents", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storeApiKey(provider: string, apiKey: string) : Promise<Result<ApiKeyResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_api_key", { provider, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteApiKey(provider: string) : Promise<Result<ApiKeyResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels() : Promise<Result<ModelsResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateModelPreference(provider: string, model: string, enabled: boolean) : Promise<Result<ModelToggle, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_model_preference", { provider, model, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(data: FolderCreate) : Promise<Result<FolderResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFolder(folderId: string) : Promise<Result<FolderResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder", { folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFolder(folderId: string, data: FolderUpdate) : Promise<Result<FolderResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_folder", { folderId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFolder(folderId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDocuments(folderId: string, limit: number | null, offset: number | null) : Promise<Result<DocumentResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_documents", { folderId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDocument(documentId: string) : Promise<Result<DocumentResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDocument(documentId: string, data: DocumentUpdate) : Promise<Result<DocumentResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_document", { documentId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDocument(documentId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_document", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDocumentStatus(documentId: string) : Promise<Result<DocumentStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_document_status", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDocumentPdfPath(documentId: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_document_pdf_path", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDocuments(request: ImportDocumentRequest) : Promise<Result<string[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_documents", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChats(documentId: string, limit: number | null, offset: number | null) : Promise<Result<Chat[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chats", { documentId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChat(documentId: string, chatId: string) : Promise<Result<Chat, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chat", { documentId, chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChat(documentId: string, data: ChatCreate) : Promise<Result<Chat, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chat", { documentId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateChat(documentId: string, chatId: string, data: ChatUpdate) : Promise<Result<Chat, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_chat", { documentId, chatId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteChat(documentId: string, chatId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_chat", { documentId, chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessages(documentId: string, chatId: string, limit: number | null) : Promise<Result<MessageResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_messages", { documentId, chatId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamChat(request: StreamChatRequest, onEvent: TAURI_CHANNEL<ChatStreamEvent>) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_chat", { request, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Structured API error with error codes for frontend handling
 */
export type ApiError = { 
/**
 * Error code for programmatic handling (e.g., "NOT_FOUND", "INVALID_INPUT")
 */
code: string; 
/**
 * Human-readable error message
 */
message: string }
export type ApiKeyResponse = { provider: string; has_provided_key: boolean }
export type Chat = { id: string; document_id: string; title: string; created_at: string; updated_at: string }
export type ChatCreate = { title: string | null }
export type ChatStreamEvent = { event: "UserMessageSaved"; message_id: string } | { event: "Chunk"; content: string } | { event: "Done"; message_id: string } | { event: "TitleUpdated"; chat_id: string; title: string; updated_at: string } | { event: "Error"; message: string }
export type ChatUpdate = { title: string | null }
export type DocumentResponse = { id: string; folder_id: string; title: string; file_path: string | null; status: string; error_details: string | null; total_pages: number; embeddings_complete: boolean; created_at: string; updated_at: string; accessed_at: string; completed_at: string | null }
export type DocumentStatus = { status: string; error_details: string | null }
export type DocumentUpdate = { title: string | null; folder_id: string | null; accessed_at: string | null }
export type FolderCreate = { title: string; description: string | null; is_default: boolean | null }
export type FolderResponse = { id: string; title: string; description: string; is_default: boolean; created_at: string; updated_at: string }
export type FolderUpdate = { title: string | null; description: string | null }
export type ImportDocumentRequest = { file_paths: string[]; folder_id: string | null }
export type MessageResponse = { id: string; chat_id: string; role: string; parts: string; metadata: string; created_at: string }
export type ModelToggle = { id: string; name: string; enabled: boolean }
export type ModelsResponse = { providers: ProviderModels[] }
export type ProviderModels = { provider: string; models: ModelToggle[] }
export type RecentDocument = { document_id: string; folder_id: string; title: string }
export type RecentDocumentsResponse = { documents: RecentDocument[]; total_count: number }
export type StreamChatRequest = { document_id: string; chat_id: string; message: string; model: string }
export type TAURI_CHANNEL<TSend> = null
export type UserFolder = { id: string; title: string; description: string; is_default: boolean; updated_at: string; documents?: UserFolderDocument[] | null }
export type UserFolderDocument = { id: string; title: string; status: string; folder_id: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
