/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AppFolderFolderIdRouteImport } from "./routes/_app/folder.$folderId"
import { Route as AppDocumentDocumentIdRouteImport } from "./routes/_app/document.$documentId"

const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppFolderFolderIdRoute = AppFolderFolderIdRouteImport.update({
  id: "/folder/$folderId",
  path: "/folder/$folderId",
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentDocumentIdRoute = AppDocumentDocumentIdRouteImport.update({
  id: "/document/$documentId",
  path: "/document/$documentId",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/onboarding": typeof OnboardingRoute
  "/document/$documentId": typeof AppDocumentDocumentIdRoute
  "/folder/$folderId": typeof AppFolderFolderIdRoute
}
export interface FileRoutesByTo {
  "/onboarding": typeof OnboardingRoute
  "/": typeof AppIndexRoute
  "/document/$documentId": typeof AppDocumentDocumentIdRoute
  "/folder/$folderId": typeof AppFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/onboarding": typeof OnboardingRoute
  "/_app/": typeof AppIndexRoute
  "/_app/document/$documentId": typeof AppDocumentDocumentIdRoute
  "/_app/folder/$folderId": typeof AppFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/onboarding" | "/document/$documentId" | "/folder/$folderId"
  fileRoutesByTo: FileRoutesByTo
  to: "/onboarding" | "/" | "/document/$documentId" | "/folder/$folderId"
  id:
    | "__root__"
    | "/_app"
    | "/onboarding"
    | "/_app/"
    | "/_app/document/$documentId"
    | "/_app/folder/$folderId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/folder/$folderId": {
      id: "/_app/folder/$folderId"
      path: "/folder/$folderId"
      fullPath: "/folder/$folderId"
      preLoaderRoute: typeof AppFolderFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/document/$documentId": {
      id: "/_app/document/$documentId"
      path: "/document/$documentId"
      fullPath: "/document/$documentId"
      preLoaderRoute: typeof AppDocumentDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDocumentDocumentIdRoute: typeof AppDocumentDocumentIdRoute
  AppFolderFolderIdRoute: typeof AppFolderFolderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDocumentDocumentIdRoute: AppDocumentDocumentIdRoute,
  AppFolderFolderIdRoute: AppFolderFolderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
